# Generated by Django 3.1.7 on 2021-03-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210309_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mailcheck',
        ),
    ]
