# Generated by Django 3.1.7 on 2021-03-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
