# Generated by Django 3.1.7 on 2021-03-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
