# Generated by Django 3.1.7 on 2021-03-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h_work_15', '0006_auto_20210312_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
