# Generated by Django 3.1.7 on 2021-03-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_work_15', '0007_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=80, verbose_name='Тема письма*')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваша почта*')),
                ('body', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
